### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by etharendil** [jsen-/kx#1] opened 2019-09-19 14:13 UTC
hi,

myself Ondrish tried to working kx but it was not fruitful  and getting errors  my windows machine
```
(venv) ~/projects/caas/cluster-requests (flavor_req_option) $ ./kx
-bash: ./kx: cannot execute binary file```
plz fix

**Comment by etharendil** [comment] 2019-09-19 14:15
Hi

**Comment by etharendil** [comment] 2019-09-19 14:15
any uptdate ?

**Comment by etharendil** [comment] 2019-09-19 14:18
still not working

**Comment by etharendil** [comment] 2019-09-19 14:19
u there ?

**Comment by jsen-** [comment] 2019-09-19 14:27
unable to reproduce
closing

**Closed as completed by jsen-** 2019-09-19 14:27 UTC
